import * as path from 'path';
import { User } from '../db/models/User';
import { initializeStore } from '../db/config';
import { capitalizeEachFirstLetter, getNowUtc } from '../utils';
import { IUser } from '../interfaces/users';
// var Mailchimp = require('mailchimp-api-v3');
import { find, slice, chunk, uniqBy, uniq } from 'lodash';
import { PatchByQueryOperation } from 'ravendb';
import { getIdWithoutCollection, getAncestorsWithCollection, getAncestorsAsArray, appendUserIdToAncestors, getAncestorLevelsUp } from '../helpers/user';
import { UserSubscription } from '../db/models/UserSubscription';
import moment = require('moment');
import { processInvoiceUpdated } from '../helpers/stripe';
import { StripeWebhook } from '../db/models/Stripe';
import * as Stripe from 'stripe';
import { IWebhook, Webhook } from '../interfaces/stripe';

const orders: any[] = [
  {
    id: 'evt_1DRNO4BoNKcVzRvk9JIlwzBp',
    object: 'event',
    api_version: '2017-08-15',
    created: 1541006508,
    data: {
      object: {
        id: 'in_1DQdTbBoNKcVzRvkhtS3LCON',
        object: 'invoice',
        amount_due: 4700,
        amount_paid: 4700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 2,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DRNO1BoNKcVzRvkE8x8eqJ8',
        closed: true,
        currency: 'usd',
        customer: 'cus_DplejJTFoqoYwM',
        date: 1540830027,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_1Xx7knqwnQtttBs3k14mmRQ8Tw',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_1Xx7knqwnQtttBs3k14mmRQ8Tw/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DplfZb0HHIw5SW',
              object: 'line_item',
              amount: 4700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543508360,
                start: 1540829960,
              },
              plan: {
                id: 'plan_DoHwC0xJk95mgg',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 4700,
                billing_scheme: 'per_unit',
                created: 1539883964,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PLUS CMD',
                nickname: 'TVI - PLUS CMD',
                product: 'prod_DoHw8GFyjxKHj8',
                statement_descriptor: 'TVI - PLUS CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DplfkKaDVHOvyR',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DQdTbBoNKcVzRvkhtS3LCON/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: 'D9121E6-0002',
        paid: true,
        period_end: 1540829960,
        period_start: 1540225160,
        receipt_number: '2957-5805',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DplfZb0HHIw5SW',
        subtotal: 4700,
        tax: 0,
        tax_percent: null,
        total: 4700,
        webhooks_delivered_at: 1540830029,
      },
    },
    livemode: true,
    pending_webhooks: 2,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DQiqKBoNKcVzRvklUJ6QclX',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540850656,
    data: {
      object: {
        id: 'in_1DQht9BoNKcVzRvkI3q1AnXJ',
        object: 'invoice',
        amount_due: 4700,
        amount_paid: 4700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DQiqIBoNKcVzRvkWBxWorvg',
        closed: true,
        currency: 'usd',
        customer: 'cus_DpqC6yIM1UCg9f',
        date: 1540846987,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_vhZ8LxLak1oFdTSh4CCzoRfXez',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_vhZ8LxLak1oFdTSh4CCzoRfXez/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DpqCxa6tqg8cnS',
              object: 'line_item',
              amount: 4700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543525260,
                start: 1540846860,
              },
              plan: {
                id: 'plan_DoHwC0xJk95mgg',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 4700,
                billing_scheme: 'per_unit',
                created: 1539883964,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PLUS CMD',
                nickname: 'TVI - PLUS CMD',
                product: 'prod_DoHw8GFyjxKHj8',
                statement_descriptor: 'TVI - PLUS CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DpqCCTKmyFofBc',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DQht9BoNKcVzRvkI3q1AnXJ/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: 'F4073EE-0002',
        paid: true,
        period_end: 1540846860,
        period_start: 1540242060,
        receipt_number: '2980-5666',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DpqCxa6tqg8cnS',
        subtotal: 4700,
        tax: 0,
        tax_percent: null,
        total: 4700,
        webhooks_delivered_at: 1540846994,
      },
    },
    livemode: true,
    pending_webhooks: 3,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DQoIyBoNKcVzRvkr1xNAub1',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540871652,
    data: {
      object: {
        id: 'in_1DQnMDBoNKcVzRvkjIIprCNw',
        object: 'invoice',
        amount_due: 4700,
        amount_paid: 4700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DQoIwBoNKcVzRvk397yuYiF',
        closed: true,
        currency: 'usd',
        customer: 'cus_Dpvr3lTlNYh0rD',
        date: 1540868009,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_lbhWW4xummEUuZKzf9MbSDTomQ',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_lbhWW4xummEUuZKzf9MbSDTomQ/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DpvroYqKLbABk8',
              object: 'line_item',
              amount: 4700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543546286,
                start: 1540867886,
              },
              plan: {
                id: 'plan_DoHwC0xJk95mgg',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 4700,
                billing_scheme: 'per_unit',
                created: 1539883964,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PLUS CMD',
                nickname: 'TVI - PLUS CMD',
                product: 'prod_DoHw8GFyjxKHj8',
                statement_descriptor: 'TVI - PLUS CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DpvruiCCKlr754',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DQnMDBoNKcVzRvkjIIprCNw/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: 'F0C9728-0002',
        paid: true,
        period_end: 1540867886,
        period_start: 1540263086,
        receipt_number: '2712-4651',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DpvroYqKLbABk8',
        subtotal: 4700,
        tax: 0,
        tax_percent: null,
        total: 4700,
        webhooks_delivered_at: 1540868014,
      },
    },
    livemode: true,
    pending_webhooks: 3,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DRALGBoNKcVzRvknijTINb2',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540956362,
    data: {
      object: {
        id: 'in_1DR9NSBoNKcVzRvkF0O4L8KS',
        object: 'invoice',
        amount_due: 4700,
        amount_paid: 4700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DRALEBoNKcVzRvk9nc7Q54f',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqIceeTI8lDkfw',
        date: 1540952653,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_ABlEU5q6XNyTbaZbN7SFHxju0v',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_ABlEU5q6XNyTbaZbN7SFHxju0v/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqIcA9tshopxLH',
              object: 'line_item',
              amount: 4700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543544557,
                start: 1540952557,
              },
              plan: {
                id: 'plan_DoHwC0xJk95mgg',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 4700,
                billing_scheme: 'per_unit',
                created: 1539883964,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PLUS CMD',
                nickname: 'TVI - PLUS CMD',
                product: 'prod_DoHw8GFyjxKHj8',
                statement_descriptor: 'TVI - PLUS CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqIcPyeXaUce2u',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DR9NSBoNKcVzRvkF0O4L8KS/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '5CD3CA8-0002',
        paid: true,
        period_end: 1540952557,
        period_start: 1540347757,
        receipt_number: '2549-3756',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqIcA9tshopxLH',
        subtotal: 4700,
        tax: 0,
        tax_percent: null,
        total: 4700,
        webhooks_delivered_at: 1540952657,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DRLeSBoNKcVzRvkMn1OlBj3',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540999836,
    data: {
      object: {
        id: 'in_1DRLeQBoNKcVzRvkRetRdB6r',
        object: 'invoice',
        amount_due: 4700,
        amount_paid: 4700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_update',
        charge: 'ch_1DRLeQBoNKcVzRvkbAS9TWta',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqYoWgUKUYqFMe',
        date: 1540999834,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_zNHaGwvH8WtLTUTI25PSpH9QrP',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_zNHaGwvH8WtLTUTI25PSpH9QrP/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqYoGQBTNsuV5W',
              object: 'line_item',
              amount: 4700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543591834,
                start: 1540999834,
              },
              plan: {
                id: 'plan_DoHwC0xJk95mgg',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 4700,
                billing_scheme: 'per_unit',
                created: 1539883964,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PLUS CMD',
                nickname: 'TVI - PLUS CMD',
                product: 'prod_DoHw8GFyjxKHj8',
                statement_descriptor: 'TVI - PLUS CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqYowAAEjhfz5V',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DRLeQBoNKcVzRvkRetRdB6r/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: 'AF37FD1-0002',
        paid: true,
        period_end: 1540999834,
        period_start: 1540999834,
        receipt_number: '2126-6210',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqYoGQBTNsuV5W',
        subtotal: 4700,
        tax: 0,
        tax_percent: null,
        total: 4700,
        webhooks_delivered_at: null,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: 'req_I0vZguWitLcXok',
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DR6PLBoNKcVzRvkBMMEge2i',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540941239,
    data: {
      object: {
        id: 'in_1DR5T2BoNKcVzRvknJ5GerYY',
        object: 'invoice',
        amount_due: 4700,
        amount_paid: 4700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DR6PJBoNKcVzRvkbZIqmP4M',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqEaw9BRF9BjN3',
        date: 1540937624,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_wGIqpvP2ShWFiIBYFVxB2WSJOh',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_wGIqpvP2ShWFiIBYFVxB2WSJOh/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqEaAg2iOTeltP',
              object: 'line_item',
              amount: 4700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543615945,
                start: 1540937545,
              },
              plan: {
                id: 'plan_DoHwC0xJk95mgg',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 4700,
                billing_scheme: 'per_unit',
                created: 1539883964,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PLUS CMD',
                nickname: 'TVI - PLUS CMD',
                product: 'prod_DoHw8GFyjxKHj8',
                statement_descriptor: 'TVI - PLUS CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqEaiYTLIYjQVo',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DR5T2BoNKcVzRvknJ5GerYY/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '1FB2C06-0002',
        paid: true,
        period_end: 1540937545,
        period_start: 1540332745,
        receipt_number: '2051-0220',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqEaAg2iOTeltP',
        subtotal: 4700,
        tax: 0,
        tax_percent: null,
        total: 4700,
        webhooks_delivered_at: 1540937628,
      },
    },
    livemode: true,
    pending_webhooks: 3,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DRLmOBoNKcVzRvk7iYSafEn',
    object: 'event',
    api_version: '2017-08-15',
    created: 1541000327,
    data: {
      object: {
        id: 'in_1DRLmMBoNKcVzRvk3AqqLgQ1',
        object: 'invoice',
        amount_due: 4700,
        amount_paid: 4700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_update',
        charge: 'ch_1DRLmMBoNKcVzRvkSUpLCzDa',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqxxBxTI4UN6rF',
        date: 1541000325,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_6Vo0huVaz2lceT4icjGdgn5E7z',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_6Vo0huVaz2lceT4icjGdgn5E7z/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqxxX8tYvXk7ta',
              object: 'line_item',
              amount: 4700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543592325,
                start: 1541000325,
              },
              plan: {
                id: 'plan_DoHwC0xJk95mgg',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 4700,
                billing_scheme: 'per_unit',
                created: 1539883964,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PLUS CMD',
                nickname: 'TVI - PLUS CMD',
                product: 'prod_DoHw8GFyjxKHj8',
                statement_descriptor: 'TVI - PLUS CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqxxsVyWts0tDz',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DRLmMBoNKcVzRvk3AqqLgQ1/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '845364C-0002',
        paid: true,
        period_end: 1541000325,
        period_start: 1541000325,
        receipt_number: '2663-7964',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqxxX8tYvXk7ta',
        subtotal: 4700,
        tax: 0,
        tax_percent: null,
        total: 4700,
        webhooks_delivered_at: null,
      },
    },
    livemode: true,
    pending_webhooks: 3,
    request: {
      id: 'req_AGUWiewyetH80A',
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },

  {
    id: 'evt_1DQdmxBoNKcVzRvkd55dQc60',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540831227,
    data: {
      object: {
        id: 'in_1DQcpIBoNKcVzRvkwzXyLDhf',
        object: 'invoice',
        amount_due: 9700,
        amount_paid: 9700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DQdmuBoNKcVzRvkmekPkrA8',
        closed: true,
        currency: 'usd',
        customer: 'cus_Dpkxc4itAFWmjj',
        date: 1540827528,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_DoKhEhGDwbcrkUNSxj3SrMqtw8',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_DoKhEhGDwbcrkUNSxj3SrMqtw8/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DpkxMG70sHEtvI',
              object: 'line_item',
              amount: 9700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543505759,
                start: 1540827359,
              },
              plan: {
                id: 'plan_DoHwqTyXHy39xu',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 9700,
                billing_scheme: 'per_unit',
                created: 1539883988,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PRO CMD',
                nickname: 'TVI - PRO CMD',
                product: 'prod_DoHwk2XAIV8m5F',
                statement_descriptor: 'TVI - PRO CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_Dpkxcanto3uScf',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DQcpIBoNKcVzRvkwzXyLDhf/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '778D229-0002',
        paid: true,
        period_end: 1540827359,
        period_start: 1540222559,
        receipt_number: '2908-4111',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DpkxMG70sHEtvI',
        subtotal: 9700,
        tax: 0,
        tax_percent: null,
        total: 9700,
        webhooks_delivered_at: 1540827537,
      },
    },
    livemode: true,
    pending_webhooks: 3,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DR2zuBoNKcVzRvk5q1EMLZx',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540928130,
    data: {
      object: {
        id: 'in_1DR22EBoNKcVzRvkMtaMgqFS',
        object: 'invoice',
        amount_due: 9700,
        amount_paid: 9700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DR2zsBoNKcVzRvkA0TMSf8b',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqB2bQqkCi29NR',
        date: 1540924430,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_zlCTN9XxyBGyll7VPqBd4LaaPj',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_zlCTN9XxyBGyll7VPqBd4LaaPj/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqB2pXPdRQwxnz',
              object: 'line_item',
              amount: 9700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543602764,
                start: 1540924364,
              },
              plan: {
                id: 'plan_DoHwqTyXHy39xu',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 9700,
                billing_scheme: 'per_unit',
                created: 1539883988,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PRO CMD',
                nickname: 'TVI - PRO CMD',
                product: 'prod_DoHwk2XAIV8m5F',
                statement_descriptor: 'TVI - PRO CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqB2qBR58b0AoN',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DR22EBoNKcVzRvkMtaMgqFS/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '230AB56-0002',
        paid: true,
        period_end: 1540924364,
        period_start: 1540319564,
        receipt_number: '2430-5479',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqB2pXPdRQwxnz',
        subtotal: 9700,
        tax: 0,
        tax_percent: null,
        total: 9700,
        webhooks_delivered_at: 1540924433,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DRBa6BoNKcVzRvkGvLDZDP8',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540961126,
    data: {
      object: {
        id: 'in_1DRAbuBoNKcVzRvkicAuShBg',
        object: 'invoice',
        amount_due: 9700,
        amount_paid: 9700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DRBa4BoNKcVzRvkVknQn8J8',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqJuLcRwOB4wuy',
        date: 1540957394,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_g4CG1HGsrdjg1NtLFNQ5Q11xul',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_g4CG1HGsrdjg1NtLFNQ5Q11xul/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqJuIhFcQp943y',
              object: 'line_item',
              amount: 9700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543549368,
                start: 1540957368,
              },
              plan: {
                id: 'plan_DoHwqTyXHy39xu',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 9700,
                billing_scheme: 'per_unit',
                created: 1539883988,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PRO CMD',
                nickname: 'TVI - PRO CMD',
                product: 'prod_DoHwk2XAIV8m5F',
                statement_descriptor: 'TVI - PRO CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqJuoqTFGxVoEo',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DRAbuBoNKcVzRvkicAuShBg/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '7F0DA4B-0002',
        paid: true,
        period_end: 1540957368,
        period_start: 1540352568,
        receipt_number: '2601-3510',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqJuIhFcQp943y',
        subtotal: 9700,
        tax: 0,
        tax_percent: null,
        total: 9700,
        webhooks_delivered_at: 1540957398,
      },
    },
    livemode: true,
    pending_webhooks: 3,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DRLkDBoNKcVzRvkxrs1XeAO',
    object: 'event',
    api_version: '2017-08-15',
    created: 1541000193,
    data: {
      object: {
        id: 'in_1DRLkBBoNKcVzRvkSSrL9q1M',
        object: 'invoice',
        amount_due: 9700,
        amount_paid: 9700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_update',
        charge: 'ch_1DRLkBBoNKcVzRvkGVIB5Fpu',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqhGJHdXQdvoVb',
        date: 1541000191,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_lcBogt5rpC5RxOLldO30SLaXmL',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_lcBogt5rpC5RxOLldO30SLaXmL/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqhGPqormLjOv3',
              object: 'line_item',
              amount: 9700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543592191,
                start: 1541000191,
              },
              plan: {
                id: 'plan_DoHwqTyXHy39xu',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 9700,
                billing_scheme: 'per_unit',
                created: 1539883988,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PRO CMD',
                nickname: 'TVI - PRO CMD',
                product: 'prod_DoHwk2XAIV8m5F',
                statement_descriptor: 'TVI - PRO CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqhGKiOjX9I2fg',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DRLkBBoNKcVzRvkSSrL9q1M/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '0211BEF-0002',
        paid: true,
        period_end: 1541000191,
        period_start: 1541000191,
        receipt_number: '2235-2574',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqhGPqormLjOv3',
        subtotal: 9700,
        tax: 0,
        tax_percent: null,
        total: 9700,
        webhooks_delivered_at: null,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: 'req_whZVlTVHnwKGZ8',
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DRLlSBoNKcVzRvkJEMt7yni',
    object: 'event',
    api_version: '2017-08-15',
    created: 1541000270,
    data: {
      object: {
        id: 'in_1DRLlQBoNKcVzRvk6NYfOYcQ',
        object: 'invoice',
        amount_due: 9700,
        amount_paid: 9700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_update',
        charge: 'ch_1DRLlQBoNKcVzRvkBSCFTsuG',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqlcjMv587TD8U',
        date: 1541000268,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_skolh5QYIkPBfbL1OhK8aNoLbG',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_skolh5QYIkPBfbL1OhK8aNoLbG/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_Dqlc71PMjTzgaV',
              object: 'line_item',
              amount: 9700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543592268,
                start: 1541000268,
              },
              plan: {
                id: 'plan_DoHwqTyXHy39xu',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 9700,
                billing_scheme: 'per_unit',
                created: 1539883988,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PRO CMD',
                nickname: 'TVI - PRO CMD',
                product: 'prod_DoHwk2XAIV8m5F',
                statement_descriptor: 'TVI - PRO CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_Dqlc6oH1ayJxB9',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DRLlQBoNKcVzRvk6NYfOYcQ/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '9775247-0002',
        paid: true,
        period_end: 1541000268,
        period_start: 1541000268,
        receipt_number: '2119-5060',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_Dqlc71PMjTzgaV',
        subtotal: 9700,
        tax: 0,
        tax_percent: null,
        total: 9700,
        webhooks_delivered_at: null,
      },
    },
    livemode: true,
    pending_webhooks: 2,
    request: {
      id: 'req_ZSKXy9qQVMZiBY',
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DQz3gBoNKcVzRvkanruGRT5',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540912988,
    data: {
      object: {
        id: 'in_1DQy5vBoNKcVzRvkYBBD7Lra',
        object: 'invoice',
        amount_due: 9700,
        amount_paid: 9700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DQz3dBoNKcVzRvktozh0eEK',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqAvFovRWD3kqU',
        date: 1540909283,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_TJWhroCfJ05bTtRG6uGM3MXtCe',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_TJWhroCfJ05bTtRG6uGM3MXtCe/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DsMKmSLERAllTA',
              object: 'line_item',
              amount: 9700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1543587646,
                start: 1540909246,
              },
              plan: {
                id: 'plan_DoHwqTyXHy39xu',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 9700,
                billing_scheme: 'per_unit',
                created: 1539883988,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TVI - PRO CMD',
                nickname: 'TVI - PRO CMD',
                product: 'prod_DoHwk2XAIV8m5F',
                statement_descriptor: 'TVI - PRO CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DsMKi92cdyZcnx',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DQy5vBoNKcVzRvkYBBD7Lra/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: 'BA9F5EC-0003',
        paid: true,
        period_end: 1540909246,
        period_start: 1540822846,
        receipt_number: '2705-2564',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DsMKmSLERAllTA',
        subtotal: 9700,
        tax: 0,
        tax_percent: null,
        total: 9700,
        webhooks_delivered_at: 1540909285,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },

  {
    id: 'evt_1DQaOzBoNKcVzRvkYDsv9HiQ',
    object: 'event',
    api_version: '2017-08-15',
    created: 1540818209,
    data: {
      object: {
        id: 'in_1DQZS7BoNKcVzRvklbergyVF',
        object: 'invoice',
        amount_due: 99700,
        amount_paid: 99700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_cycle',
        charge: 'ch_1DQaOxBoNKcVzRvkSJ6BrR8f',
        closed: true,
        currency: 'usd',
        customer: 'cus_DpkajwJlacc8pR',
        date: 1540814559,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_WEk7GxwCCWVan1AzCOBLPMzcj9',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_WEk7GxwCCWVan1AzCOBLPMzcj9/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DpkaM8oNashauj',
              object: 'line_item',
              amount: 99700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1572350400,
                start: 1540814400,
              },
              plan: {
                id: 'plan_DoHxpcXYw1aiMy',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 99700,
                billing_scheme: 'per_unit',
                created: 1539884029,
                currency: 'usd',
                interval: 'year',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TripValet Annual - CMD',
                nickname: 'TripValet Annual - CMD',
                product: 'prod_DoHx7yKeIOeIeD',
                statement_descriptor: 'TripValet Annual - CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DpkanS1D2sSN4z',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DQZS7BoNKcVzRvklbergyVF/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '0D3BBB3-0002',
        paid: true,
        period_end: 1540814400,
        period_start: 1540221148,
        receipt_number: '2633-6882',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DpkaM8oNashauj',
        subtotal: 99700,
        tax: 0,
        tax_percent: null,
        total: 99700,
        webhooks_delivered_at: 1540814562,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DRqPtBoNKcVzRvkJ64EsR84',
    object: 'event',
    api_version: '2017-08-15',
    created: 1541118097,
    data: {
      object: {
        id: 'in_1DRinPBoNKcVzRvkiICE5R6p',
        object: 'invoice',
        amount_due: 90000,
        amount_paid: 90000,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'send_invoice',
        billing_reason: 'subscription_update',
        charge: 'ch_1DRqPrBoNKcVzRvkDtqIzoo1',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqBf2L8TuKITT8',
        date: 1541088803,
        description: '',
        discount: {
          object: 'discount',
          coupon: {
            id: 'BrUYdIM2',
            object: 'coupon',
            amount_off: 9700,
            created: 1541088570,
            currency: 'usd',
            duration: 'once',
            duration_in_months: null,
            livemode: true,
            max_redemptions: null,
            metadata: {},
            name: 'Member Paid 1 Month ',
            percent_off: null,
            percent_off_precise: null,
            redeem_by: null,
            times_redeemed: 1,
            valid: true,
          },
          customer: 'cus_DqBf2L8TuKITT8',
          end: null,
          start: 1541088656,
          subscription: 'sub_DtVm0IO9d7yqz2',
        },
        due_date: 1541175203,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_XZV3SG13PHA7W4Ql7m3bSbxUg7',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_XZV3SG13PHA7W4Ql7m3bSbxUg7/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DtVm0IO9d7yqz2',
              object: 'line_item',
              amount: 99700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1572624803,
                start: 1541088803,
              },
              plan: {
                id: 'plan_DoHxpcXYw1aiMy',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 99700,
                billing_scheme: 'per_unit',
                created: 1539884029,
                currency: 'usd',
                interval: 'year',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TripValet Annual - CMD',
                nickname: 'TripValet Annual - CMD',
                product: 'prod_DoHx7yKeIOeIeD',
                statement_descriptor: 'TripValet Annual - CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DtVmtMXR0dSqjN',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DRinPBoNKcVzRvkiICE5R6p/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '7C0A111-0005',
        paid: true,
        period_end: 1541088803,
        period_start: 1541088803,
        receipt_number: '2225-8789',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DtVm0IO9d7yqz2',
        subtotal: 99700,
        tax: 0,
        tax_percent: null,
        total: 90000,
        webhooks_delivered_at: 1541088810,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: 'req_AhkqwxgudlhOBL',
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
  {
    id: 'evt_1DS9m2BoNKcVzRvkZVQr6QSN',
    object: 'event',
    api_version: '2017-08-15',
    created: 1541192505,
    data: {
      object: {
        id: 'in_1DS9m0BoNKcVzRvkn4etNNmM',
        object: 'invoice',
        amount_due: 99700,
        amount_paid: 99700,
        amount_remaining: 0,
        application_fee: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing: 'charge_automatically',
        billing_reason: 'subscription_update',
        charge: 'ch_1DS9m0BoNKcVzRvkNzQXwh1w',
        closed: true,
        currency: 'usd',
        customer: 'cus_DqLNqaFBghEEte',
        date: 1541192503,
        description: '',
        discount: null,
        due_date: null,
        ending_balance: 0,
        forgiven: false,
        hosted_invoice_url: 'https://pay.stripe.com/invoice/invst_HHcPbnYS5ssd6ktaJzBgkE9UeO',
        invoice_pdf: 'https://pay.stripe.com/invoice/invst_HHcPbnYS5ssd6ktaJzBgkE9UeO/pdf',
        lines: {
          object: 'list',
          data: [
            {
              id: 'sub_DqLNsmBtqSyOWK',
              object: 'line_item',
              amount: 99700,
              currency: 'usd',
              description: null,
              discountable: true,
              livemode: true,
              metadata: {},
              period: {
                end: 1572728503,
                start: 1541192503,
              },
              plan: {
                id: 'plan_DoHxpcXYw1aiMy',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 99700,
                billing_scheme: 'per_unit',
                created: 1539884029,
                currency: 'usd',
                interval: 'year',
                interval_count: 1,
                livemode: true,
                metadata: {},
                name: 'TripValet Annual - CMD',
                nickname: 'TripValet Annual - CMD',
                product: 'prod_DoHx7yKeIOeIeD',
                statement_descriptor: 'TripValet Annual - CMD',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: 7,
                usage_type: 'licensed',
              },
              proration: false,
              quantity: 1,
              subscription: null,
              subscription_item: 'si_DqLN8O5BK7JHSC',
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1DS9m0BoNKcVzRvkn4etNNmM/lines',
        },
        livemode: true,
        metadata: {},
        next_payment_attempt: null,
        number: '420140B-0002',
        paid: true,
        payment_intent: null,
        period_end: 1541192503,
        period_start: 1541192503,
        receipt_number: '2583-0834',
        starting_balance: 0,
        statement_descriptor: null,
        subscription: 'sub_DqLNsmBtqSyOWK',
        subtotal: 99700,
        tax: 0,
        tax_percent: null,
        total: 99700,
        webhooks_delivered_at: null,
      },
    },
    livemode: true,
    pending_webhooks: 1,
    request: {
      id: 'req_Qlm8EKH231k8Y0',
      idempotency_key: null,
    },
    type: 'invoice.payment_succeeded',
  },
];

(async () => {
  try {
    const store = await initializeStore();

    try {
      let session = store.openSession();
      const orders = await session
        .query<StripeWebhook>({ collection: 'StripeWebHooks' })
        .whereEquals('type', 'invoice.payment_succeeded')
        .selectFields(['webhook'])
        .ofType<IWebhook>(Webhook)
        .all();
      session.dispose();

      for (let order of orders) {
        let session = store.openSession();
        await processInvoiceUpdated(session, <Stripe.events.IEvent>order.webhook);
        session.dispose();
      }
      process.exit(0);
    } catch (ex) {
      console.log(ex.message);
      process.exit(1);
    }
  } catch (ex) {
    console.log(ex.message);
    process.exit(1);
  }
})();
